### ISSUE TITLE
TODO after May 3 meeting

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/gfmpa#24]
- [x] add black line in fig 4?
- [x] add as-is where-is to fig 1
- [x] check... that domain sets are indeed dropped!!
- [x] label strata?
- [x] thin or more alpha on black in stratum figure?
- [x] flip tweedie and delta-gamma order in modelling
- [ ] note that in HS: MARE is better with geostatistical:
- [x] make new fig 4 for design based that matches the geostationary version
(non-free axis and side by side??)
- [ ] fig 5: proportions driven by increases or decreases inside vs. outside?
- [x] fig 5: right now, panels b-f are ordered by their position on the x-axis. Consider reordering to make them ordered by the y-axis because they are positioned vertically. This would just involve switching d and e.
